version: "3"
services:
  rabbitmq-1:
    image: rabbitmq:3.8-management
    container_name: rabbit-1
    hostname: rabbit-1
    ports:
      - "8081:15672"
      - "5672:5672"
    volumes:
      - ./config/rabbit-1:/config
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW
    networks:
      - rabbits
  rabbitmq-2:
    image: rabbitmq:3.8-management
    container_name: rabbit-2
    hostname: rabbit-2
    ports:
      - "8082:15672"
      - "35673:5672"
    volumes:
      - ./config/rabbit-2:/config
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW
    networks:
      - rabbits
  rabbitmq-3:
    image: rabbitmq:3.8-management
    container_name: rabbit-3
    hostname: rabbit-3
    ports:
      - "8083:15672"
      - "35674:5672"
    volumes:
      - ./config/rabbit-3:/config
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW
    networks:
      - rabbits
networks:
  rabbits: